# Generated by Django 5.0.2 on 2024-02-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
