# Generated by Django 4.2.2 on 2024-02-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(max_length=12)),
                ('closed', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='todotask',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='todoApp.taskstatus'),
            preserve_default=False,
        ),
    ]
